volumes:
  email_otp_postgres_data:
    driver: local

services:
  postgres:
    volumes:
      - email_otp_postgres_data:/var/lib/postgresql/data
    hostname: postgres
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    restart: always

  keycloak:
    hostname: keycloak
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_HOST: postgres
      KC_DB_PORT: 5432
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start
      - --cache-stack=tcp
    ports:
      - '8080:8080'
    volumes:
      - ./target/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:ro
      - ./themes:/opt/keycloak/themes
    depends_on:
      - postgres